### ISSUE TITLE
Add Somatic Validation tracks to DumpIgvXml ClinSeq command.

### ISSUE THREAD

**Issue by jasonwalker80** [genome/genome#1409]
The DumpIgvXml command relies on finding the tumor_build and normal_build which only exist as ReferenceAlignment builds on Somatic Variation inputs.  The DumpIgvXml command should resolve the path to the tumor/normal bed/bam file for all somatic model types.

**Comment by susannasiebert** [comment]
I have some code in a checkout that adds bams for somatic validation builds. I ran a test build with that change (403da3ae3db144b1829e28a2a0c64ffa). I would appreciate it if someone could have a look at the IGV files and confirm that they look as expected. @jasonwalker80 @gatoravi

**Comment by gatoravi** [comment]
I can confirm that the level1 and level3 IGV session files work as expected and look great. IGV freezes up when I try the level7 file, could someone confirm that this is probably an issue on my end, I have the same issue with the level5 sessions. Both these load files from the `variants` folder as opposed to just the `effects` folder, perhaps that has something to do with this? 
(alternatively perhaps the level7/level5 have a problem in the builds using som-var as well)

I've only ever used level1 for analysis but perhaps there are people who use other levels.

**Comment by susannasiebert** [comment]
I opened the igv file in a vim session (as opposed to in the igv browser) and it looks like all the variants files are bed files. The processing of bed files hasn't changed. These levels are loading twice as many files so it's conceivable that you might be running out RAM. What's the command you used to open these files?

**Comment by gatoravi** [comment]
That does make sense. I copied the files locally, opened up IGV. File->Open Session and chose the session file.

**Comment by susannasiebert** [comment]
I tried opening that file on my machine and I get a "Memory is low, reading terminating" message.

**Comment by gatoravi** [comment]
Yeah ok, I think this is probably fine then.
