### ISSUE TITLE
Add Exome Variant Project MAF information to the Clinseq SnvIndelReport

### ISSUE THREAD

**Issue by jasonwalker80** [genome/genome#1421]
From JIRA CI-110 requested by @chrisamiller :
We'd like to have the results from "gmt annotate add-evs-maf" to the SnvIndel report. That's the one set of info that my group often uses that is absent from the current implementation.

**Comment by chrisamiller** [comment]
The logical place for the three added columns from this tool is between the "GMAF" and "tier" columns

**Comment by jasonwalker80** [comment]
This will be a feature of new pipelines, but we likely won't get to this feature in old ClinSeq workflows.
