### ISSUE TITLE
VcfToBed.pm 1-based flag appears broken

### ISSUE THREAD

**Issue by zlskidmore** [genome/genome#1450]
Hi, using `gmt bed convert vcf-to-bed --one-based` flag appears to still ouput 0-based coordinates:

input:
9       34795908        .       CT      C       .       . 

example output:
9       34795908        34795909        T/\*     -       -

should be:
9       34795909       34795909        T/\*     -       -

**Comment by zlskidmore** [comment]
apologies, on a second look it looks like it does the proper conversion CT/C -> T/- but in the start/stop field it doesn't take into account that the VCF the coordinate is as the C while in the converted file it should start at the T

**Comment by jasonwalker80** [comment]
#1557 is now merged.  This should be resolved in the next genome snapshot.
