### ISSUE TITLE
New docker image with updated SSL implementation for GDC queries

### ISSUE THREAD

**Issue by jasonwalker80** [genome/genome#1513]
See the following work-around PR for details:
https://github.com/genome/genome/pull/1511

@tmooney : "The underlying problem is that lucid is too old for the required OpenSSL version"

**Comment by jasonwalker80** [comment]
Closing. As part of #1962 and and #1969 this should ultimately be addressed in new compute environments.

**Comment by tmooney** [comment]
For whatever it's worth, this bit should be working fine in the existing `xenial`-based image, too. :smile:
