### ISSUE TITLE
Support GRCh38 with alts

### ISSUE THREAD

**Issue by jasonwalker80** [genome/genome#1537]
Initial work was done by @ernfrid  here:
https://github.com/genome/genome/pull/1294

BWA docs : https://github.com/lh3/bwa/blob/master/README-alt.md

GATK Blog : https://software.broadinstitute.org/gatk/blog?id=8180

ReferenceSequence models will need to support auxiliary files required by downstream tools to correctly process the alt alignments.

A new version of SpeedSeq is near completion.  This includes a new version of BWA that supports alt contigs.

Completion of this Epic requires successful SomaticValidation, RNA-seq, ClinSeq and SingleSampleGenotype builds ran using HCC1395 test data.  See existing ClinSeq AnP for data:
 http://spectacle.gsc.wustl.edu/analysis_projects/ef89d9e8c1f942c492a288e5b1b4b078

**Comment by jasonwalker80** [comment]
@apregier any insights you can provide as to the changes needed in regards to ReferenceSequence models?

**Comment by apregier** [comment]
I think Dave's issue pretty much captures most it.  The main thing I have done since then is to update the bwa version to one that inserts an AH tag in the sequence header to indicate which reference sequences were treated as alts.  This may address some of Tom's concerns.  The other work I have been doing adds in a bunch of steps for CCDG, like BQSR.  So I don't know if you want all of that or not.  If you do, you would need to update the reference sequence index object to have both bwa indices and samtools indices.  Also I guess there are quite a few more dependencies that would need to be dealt with.

**Comment by jasonwalker80** [comment]
I'm fine with simply adding the alts file for now. #1554 will rely on this to use the correct reference.

**Comment by tmooney** [comment]
I've imported a new GRCh38 reference as `50f99e75d14340ffb5b7d21b03887637` and copied over the `.alt` file.

**Comment by jasonwalker80** [comment]
I had to map chr names between hg19 and nimb-hg19 as well as hg38 to GRCh38DH:
`/gscmnt/gc2764/cad/jwalker/scratch/GRCh38/liftOver/convert_liftover_chains.pl`

Converter for BED files created in the GMS:
```
genome model reference-sequence converter create --source-reference=108563338 --destination-reference=50f99e75d14340ffb5b7d21b03887637 --algorithm=lift_over --resource=/gscmnt/gc12001/info/model_data/chain_files/nimb-hg19ToGrch38DH/nimb-hg19ToGrch38DH.over.chain
```

```
genome model reference-sequence converter list --filter source_reference_build.id=108563338,destination_reference_build.id=50f99e75d14340ffb5b7d21b03887637
ID                                 SOURCE_REFERENCE_BUILD                  DESTINATION_REFERENCE_BUILD                                                             ALGORITHM   RESOURCE
--                                 ----------------------                  ---------------------------                                                             ---------   --------
2fecf7edcffc45a5bbd8d7927898948d   nimblegen-human-buildhg19 (108563338)   GRC-human-build38_full_analysis_set_plus_decoy_hla (50f99e75d14340ffb5b7d21b03887637)   lift_over   /gscmnt/gc12001/info/model_data/chain_files/nimb-hg19ToGrch38DH/nimb-hg19ToGrch38DH.over.chain
```

**Comment by jasonwalker80** [comment]
Importing dbsnp file:
```
genome model imported-variation-list import-variants --input-path=/gscmnt/gc2764/cad/HCC1395/toil/refseq/GRCh38DH/Homo_sapiens_assembly38.dbsnp138.vcf.gz --source-name=dbsnp --version=138 --reference-sequence-build=50f99e75d14340ffb5b7d21b03887637 --variant-type=snv --format=vcf --description=https://storage.googleapis.com/genomics-public-data/resources/broad/hg38/v0/Homo_sapiens_assembly38.dbsnp138.vcf
```

**Comment by jasonwalker80** [comment]
Closing. This was complete long ago.
