### ISSUE TITLE
Remove old mysql code

### ISSUE THREAD

**Issue by jasonwalker80** [genome/genome#1546]
There are a few remaining commands that either do no use the db_ensembl_* config or make direct connections to mysql servers.  For the former, they should be updated to use the config variables.  For the latter, we should consider removing the code or disabling the connection to mysql servers for old data sets like build36.

Consider updating:
/Model/Tools/Ensembl/Base.pm
./Model/Tools/ImportAnnotation/UpdateAnnotation.pm

Consider removing or disabling mysql connections from:
./Model/Tools/Pcap/Ace.t
./Model/Tools/Pcap/Config.pm
./Model/Tools/Sv/BreakAnnot.pl
./Model/Tools/Sv/SvAnnot.pm

**Comment by ebelter** [comment]
Removal of the Pcap tree should be OK.

**Comment by jasonwalker80** [comment]
I didn't look carefully before, it appears the `Model/Tools/ImportAnnotation` tree could be removed entirely as well.

**Comment by tmooney** [comment]
SvAnnot.pm is part of the DV2 TigraValidation filter.

**Comment by jasonwalker80** [comment]
Instead of removing the files, I was thinking we'd remove the code that connects to the DB.  For example, in SvAnnot perhaps we remove the `repeat_mask` option.  It only works for build36 anyway which is no longer supported.

**Comment by jasonwalker80** [comment]
For BreakAnnot.pl that uses a database named `ucsc` which doesn't appear to be versions by reference build.  Is this still run during DV2 TigraValidation.  If so, I can't imagine how it is still working.

**Comment by jasonwalker80** [comment]
For BreakAnnot.pl it appears it's used to get repeat masker annotation.  This will be WRONG for newer reference sequence builds.  I would suggest similar to SvAnnot, we remove the annotation of repeat regions from this tool.  Something like removing lines 240, 244 and the subroutine(s) that are called from 240.

**Comment by jasonwalker80** [comment]
I agree BreakAnnot.pl should go.  I confirmed the ucsc database in mysql is from build36 as well.  The knownGene entry for MUC6 matched the UCSC hg18 build.

**Comment by tmooney** [comment]
All associated have been merged.
