### ISSUE TITLE
Find and re-locate legacy software/data hiding out under `/gsc/`.

### ISSUE THREAD

**Issue by tmooney** [genome/genome#1560]
The end goal is to remove the dependency on `/gsc/` as a special directory for the GMS.
- Some software/versions might be old enough we don't need them any more.
- Some will probably need to be incorporated into our Docker image somehow (maybe in a local `/gsc/` directory?)

**Comment by jasonwalker80** [comment]
@tmooney is this complete?

**Comment by tmooney** [comment]
Not really... some progress has been made, but there are many yet-to-be-resolved cases like `samtools` that are using the `sw` Genome::Config location.

**Comment by jasonwalker80** [comment]
Closing. This is replaced by #1969
