### ISSUE TITLE
Require 2FA for genome org

### ISSUE THREAD

**Issue by jasonwalker80** [genome/genome#1591]
Similar to the University IT requirement to enable 2FA, we should also require 2FA for push access to repositories. The team @genome/unauth includes the users that have not enabled 2FA.  If you'd like to remain in your teams that have push access to genome repos, please enable 2FA as soon as possible. Using the University deadline of October 31st, I'll revisit the list of users that have enabled 2FA at that time. If you have not enabled 2FA by that time, you will be removed from the teams that allow push access to any genome repo.  Also, if you'd like to be removed from the Genome org at this time to avoid future communications, please comment and I'll remove you from the Genome GitHub Organization.

**Comment by jasonwalker80** [comment]
If you need help setting up 2FA, please see:
https://help.github.com/articles/securing-your-account-with-two-factor-authentication-2fa/

**Comment by brummett** [comment]
A Github organization can require its members have 2FA turned on:
https://help.github.com/articles/requiring-two-factor-authentication-in-your-organization/

**Comment by malachig** [comment]
I have activated 2FA and removed myself from the Team: https://github.com/orgs/genome/teams/unauth

**Comment by jasonwalker80** [comment]
A reminder that users still in the @genome/unauth team have NOT enabled 2FA. Please do so by October 31st. Soon after October 31st, the genome organization will require 2FA. Members that have not enabled 2FA by then, will be removed from the organization.

**Comment by susannasiebert** [comment]
I have activated 2FA and removed myself from the Team: https://github.com/orgs/genome/teams/unauth

**Comment by kkrysiak** [comment]
I have activated 2FA and removed myself from the Team: https://github.com/orgs/genome/teams/unauth

**Comment by ahwagner** [comment]
I have activated 2FA and removed myself from the Team: https://github.com/orgs/genome/teams/unauth

**Comment by jasonwalker80** [comment]
Another reminder that after Oct 31st, I will be setting the genome github organization to require 2FA for all users in @genome/unauth.  If you have already enabled 2FA and no longer wish to receive these notifications you can Unsubscribe from this issue.

For users worried about using git from the command line and personal access tokens, be sure to use SSH instead of HTTPS when cloning a repo. The default for a repo is usually HTTPS, but once you use SSH for a repo, it seems GitHub will remember for that repo to use SSH. See quote below from GitHub docs for 2FA:

> If you are using SSH for Git authentication, rest easy: you don't need to do anything. If you are using HTTPS Git, instead of entering your password, enter a personal access token. These can be created by going to your personal access tokens page.

**Comment by dufeiyu** [comment]
I have activated 2FA and removed myself from the Team: https://github.com/orgs/genome/teams/unauth
