### ISSUE TITLE
Move-allocations that supports DeNovoAssembly Model Types

### ISSUE THREAD

**Issue by jasonwalker80** [genome/genome#1726]

**Comment by jasonwalker80** [comment]
@ebelter did you get this working in a checkout? I see that Reference Grant data was moved.

**Comment by ebelter** [comment]
I did not. Maybe Susie moved the ref grant data?

**Comment by jasonwalker80** [comment]
@ebelter can you work with the reference grant folks to ensure *ALL* of their AnPs are moved to funded storage? Otherwise this data will be taken offline.

**Comment by jasonwalker80** [comment]
Closing legacy issue.
