### ISSUE TITLE
PrepDataForTransfer and CWL Pipeline Outputs

### ISSUE THREAD

**Issue by jasonwalker80** [genome/genome#1824]
Before we process the next round of MDS data, we should add the build ID and a timestamp (creation date) for each file in the MANIFEST.

**Comment by tmooney** [comment]
I don't believe we have a reliable way to get the individual file creation times on our filesystem.
```
$ /usr/bin/stat -c '%W' /tmp/example
0
```
We could go with the build completion time?

**Comment by jasonwalker80** [comment]
build completion time would be just fine.
