### ISSUE TITLE
Input BAM file instead of build for `gmt transcriptome ercc-map-unaligned`

### ISSUE THREAD

**Issue by jasonwalker80** [genome/genome#1883]
The original implementation assumed a RnaSeq build would be used. Instead, provide the BAM path so this tool will work with CwlPipeline builds just as well as RnaSeq (or any BAM file).

**Comment by tmooney** [comment]
This looks like it already gives the choice of a build or a BAM:
https://github.com/genome/genome/blob/7cc4cafa86dc316c166f2f48e0201ed12df413b9/lib/perl/Genome/Model/Tools/Transcriptome/ErccMapUnaligned.pm#L12-L21

**Comment by jasonwalker80** [comment]
Closing. The BAM option already exists.
