### ISSUE TITLE
Move PerLaneTophat Allocations

### ISSUE THREAD

**Issue by jasonwalker80** [genome/genome#1902]
When moving allocations for a build, the class `Genome::InstrumentData::AlignmentResult::PerLaneTophat` is not in the whitelist for acceptable allocations to move. Should these files be moved along with the other allocations, ie. MergedAlignmentResults.

**Comment by tmooney** [comment]
Yes, those should get moved.  They ought to be small--just header files for reconstructing the per-lane BAM when needed.  Regardless, they are ordinary build data that should be moved like any other.

**Comment by jasonwalker80** [comment]
Am I missing something or shouldn't these results be moved already:
https://github.com/genome/genome/blob/47a780611afa4c4c1b5a968d6bff6d11daaf6d01/lib/perl/Genome/Model/Build/RnaSeq.pm#L496

**Comment by jasonwalker80** [comment]
Closing. This issue doesn't seem to be a problem with our users. Tophat is no longer used/supported.
